require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StopwordsController do

  # This should return the minimal set of attributes required to create a valid
  # Stopword. As you add validations to Stopword, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StopwordsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all stopwords as @stopwords" do
      stopword = Stopword.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stopwords).should eq([stopword])
    end
  end

  describe "GET show" do
    it "assigns the requested stopword as @stopword" do
      stopword = Stopword.create! valid_attributes
      get :show, {:id => stopword.to_param}, valid_session
      assigns(:stopword).should eq(stopword)
    end
  end

  describe "GET new" do
    it "assigns a new stopword as @stopword" do
      get :new, {}, valid_session
      assigns(:stopword).should be_a_new(Stopword)
    end
  end

  describe "GET edit" do
    it "assigns the requested stopword as @stopword" do
      stopword = Stopword.create! valid_attributes
      get :edit, {:id => stopword.to_param}, valid_session
      assigns(:stopword).should eq(stopword)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Stopword" do
        expect {
          post :create, {:stopword => valid_attributes}, valid_session
        }.to change(Stopword, :count).by(1)
      end

      it "assigns a newly created stopword as @stopword" do
        post :create, {:stopword => valid_attributes}, valid_session
        assigns(:stopword).should be_a(Stopword)
        assigns(:stopword).should be_persisted
      end

      it "redirects to the created stopword" do
        post :create, {:stopword => valid_attributes}, valid_session
        response.should redirect_to(Stopword.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stopword as @stopword" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stopword.any_instance.stub(:save).and_return(false)
        post :create, {:stopword => {}}, valid_session
        assigns(:stopword).should be_a_new(Stopword)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stopword.any_instance.stub(:save).and_return(false)
        post :create, {:stopword => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stopword" do
        stopword = Stopword.create! valid_attributes
        # Assuming there are no other stopwords in the database, this
        # specifies that the Stopword created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Stopword.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => stopword.to_param, :stopword => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested stopword as @stopword" do
        stopword = Stopword.create! valid_attributes
        put :update, {:id => stopword.to_param, :stopword => valid_attributes}, valid_session
        assigns(:stopword).should eq(stopword)
      end

      it "redirects to the stopword" do
        stopword = Stopword.create! valid_attributes
        put :update, {:id => stopword.to_param, :stopword => valid_attributes}, valid_session
        response.should redirect_to(stopword)
      end
    end

    describe "with invalid params" do
      it "assigns the stopword as @stopword" do
        stopword = Stopword.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stopword.any_instance.stub(:save).and_return(false)
        put :update, {:id => stopword.to_param, :stopword => {}}, valid_session
        assigns(:stopword).should eq(stopword)
      end

      it "re-renders the 'edit' template" do
        stopword = Stopword.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stopword.any_instance.stub(:save).and_return(false)
        put :update, {:id => stopword.to_param, :stopword => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stopword" do
      stopword = Stopword.create! valid_attributes
      expect {
        delete :destroy, {:id => stopword.to_param}, valid_session
      }.to change(Stopword, :count).by(-1)
    end

    it "redirects to the stopwords list" do
      stopword = Stopword.create! valid_attributes
      delete :destroy, {:id => stopword.to_param}, valid_session
      response.should redirect_to(stopwords_url)
    end
  end

end
